services:

  nginx:
    container_name: portal.nginx
    image: nginx:latest
    build: './nginx/'
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./..:/var/www/html
    restart: unless-stopped

  php:
    container_name: portal.php
    image: php:8.1-fpm
    build: './php/'
    expose:
       - 9000
    volumes:
      - ./..:/var/www/html
    restart: unless-stopped

  mariadb:
    container_name: portal.mariadb
    #build: './mariadb/'
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    restart: unless-stopped

  mailpit:
    container_name: portal.mailpit
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  mariadb_data:
